import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/index.module.css'
import { client } from '../libs/client'

export default function Home({ blog }) {
    return (
        <div className={styles.container}>
            <Head title={`Home`}>
                <title>horikita blog</title>
                <meta name="description" content="Generated by horikita" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    horikita blog
                </h1>
                <ul>
                    {blog.contents.map(post => (
                        <li key={post.id}>
                            <Link href={`/blog/${post.id}`}>
                                <a>{post.title}</a>
                            </Link>
                        </li>
                    ))}
                </ul>
            </main>
        </div>
    );
}

export const getStaticProps = async () => {
    const blog = await client.get({
        endpoint: 'blog',
    });

    return {
        props: {
            blog,
        },
    };
};
